name: Enviar notificaci칩n a Google Chat

on:
  pull_request:
    types: [opened, synchronize, reopened] #  pull request: abierto, sincronizado o reabierto
  push:
    branches:
      - main
jobs:
  google-chat-action:
    name: Google Chat GitHub Action
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Notify Google Chat
        if: ${{ always() }} # Asegura que se env칤e la notificaci칩n incluso si los pasos anteriores fallan
        uses: SimonScholz/google-chat-action@main # Usa la acci칩n google-chat-action para enviar un mensaje a Google Chat.
        with:
          webhookUrl: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}
          message: |
            游닉 **GitHub Notification**
            - **Repository**: ${{ github.repository }}
            - **Event**: ${{ github.event_name }}
            - **Actor**: ${{ github.actor }}
            - **Pull Request**: ${{ github.event.pull_request.html_url || 'N/A' }}
